const http = require('http');
const server = http.createServer((req, res) => {
  console.log(req.url, req.method, req.headers);
  const cssStyle = `
  <style>
    h1 {
      text-align: center;
      color: rgb(207, 63, 87);
    }

    p {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      padding-left: 20px;
      padding-right: 20px;
      background-color: lightgrey;
      padding: 20px;
    }
</style>
  `;

  const navLinks = `
    <p>
      <a href="/home">Home</a>
      <a href="/men">Men</a>
      <a href="/women">Women</a>
      <a href="/kids">Kids</a>
      <a href="/cart">Cart</a>
    </p>
  `;
  res.setHeader('Content-type', 'text/html');
  if (req.url.toLowerCase() === '/home' || req.url === '/') {
    res.write(`
      <!DOCTYPE html>
        <html lang="en">

        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Home</title>
          ${cssStyle}
        </head>

        <body>
          <h1>Myntra</h1>
          ${navLinks}
          <center><h2>Welcome to Home Section</h2></center>
        </body>

        </html>
      `);
    return res.end();
  } else if (req.url.toLowerCase() === '/men') {
    res.write(`
      <!DOCTYPE html>
        <html lang="en">

        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Men</title>
          ${cssStyle}
        </head>

        <body>
          <h1>Myntra</h1>
          ${navLinks}
          <center><h2>Welcome to Men Section</h2></center>
        </body>

        </html>
      `);
    return res.end();
  } else if (req.url.toLowerCase() === '/women') {
    res.write(`
      <!DOCTYPE html>
        <html lang="en">

        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Women</title>
          ${cssStyle}
        </head>

        <body>
          <h1>Myntra</h1>
          ${navLinks}
          <center><h2>Welcome to Women Section</h2></center>
        </body>

        </html>
      `);
    return res.end();
  } else if (req.url.toLowerCase() === '/kids') {
    res.write(`
      <!DOCTYPE html>
        <html lang="en">

        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Kids</title>
          ${cssStyle}
        </head>

        <body>
          <h1>Myntra</h1>
          ${navLinks}
          <center><h2>Welcome to Kids Section</h2></center>
        </body>

        </html>
      `);
    return res.end();
  } else if (req.url.toLowerCase() === '/cart') {
    res.write(`
      <!DOCTYPE html>
        <html lang="en">

        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Cart</title>
          ${cssStyle}
        </head>

        <body>
          <h1>Myntra</h1>
          ${navLinks}
          <center><h2>Welcome to Cart</h2></center>
        </body>

        </html>
      `);
    return res.end();
  }
  res.setHeader('Content-Type', 'text/html');
  res.write('<html>');
  res.write('<head><title>Complete Coding</title></head>');
  res.write('<body><h2>404 - Page Not Found</h2></body>');
  res.write('</html>');
  return res.end();
});

server.listen(3000, () => {
  console.log(`Server is running at http://localhost:3000`);
});

// Consice Code generated by deepseek

// const http = require('http');

// const server = http.createServer((req, res) => {
//   console.log(req.url, req.method);

//   const cssStyle = `
//     <style>
//       h1 { text-align: center; color: rgb(207, 63, 87); }
//       p {
//         display: flex;
//         justify-content: space-between;
//         background-color: lightgrey;
//         padding: 20px;
//       }
//       a { text-decoration: none; color: blue; }
//     </style>
//   `;

//   // Navigation links (same for all pages)
//   const navLinks = `
//     <p>
//       <a href="/home">Home</a>
//       <a href="/men">Men</a>
//       <a href="/women">Women</a>
//       <a href="/kids">Kids</a>
//       <a href="/cart">Cart</a>
//     </p>
//   `;

//   res.setHeader('Content-Type', 'text/html');

//   // Convert URL to lowercase for easier comparison
//   const url = req.url.toLowerCase();

//   // Object to store page information
//   const pages = {
//     '/home': { title: 'Home', message: 'Welcome to Home Section' },
//     '/men': { title: 'Men', message: 'Welcome to Men Section' },
//     '/women': { title: 'Women', message: 'Welcome to Women Section' },
//     '/kids': { title: 'Kids', message: 'Welcome to Kids Section' },
//     '/cart': { title: 'Cart', message: 'Welcome to Cart' },
//     '/': { title: 'Home', message: 'Welcome to Home Section' }
//   };

//   // Check if URL exists in pages object
//   if (pages[url]) {
//     const page = pages[url];

//     const html = `
//       <!DOCTYPE html>
//       <html lang="en">
//       <head>
//         <meta charset="UTF-8">
//         <meta name="viewport" content="width=device-width, initial-scale=1.0">
//         <title>${page.title}</title>
//         ${cssStyle}
//       </head>
//       <body>
//         <h1>Myntra</h1>
//         ${navLinks}
//         <center><h2>${page.message}</h2></center>
//       </body>
//       </html>
//     `;

//     res.write(html);
//     return res.end();
//   }

//   // If URL not found, show 404 page
//   const html = `
//     <!DOCTYPE html>
//     <html>
//     <head>
//       <title>Page Not Found</title>
//       ${cssStyle}
//     </head>
//     <body>
//       <h1>Myntra</h1>
//       ${navLinks}
//       <center>
//         <h2>404 - Page Not Found</h2>
//         <p>Like / Share / Subscribe</p>
//       </center>
//     </body>
//     </html>
//   `;

//   res.write(html);
//   res.end();
// });

// server.listen(3000, () => {
//   console.log('Server is running at http://localhost:3000');
// });
